### ISSUE TITLE
UrhoSharp Texture2D does not contain the function GetGPUObject

### ISSUE THREAD

**Issue by binxie33** [phongcao/webrtc-mrvc-sample#3]
Hi,

I tried to build the UrhoUWPDesktop project, but got the following error. The UrhoSharp NuGet Package originally specified in the project is 1.8.0, but it is not available in the NuGet server now. I use the latest version 1.8.93 but apparently its Texture2D class does not expose the GetGPUObject function. Any idea how to fix it?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Texture2D' does not contain a definition for 'GetGPUObject' and no accessible extension method 'GetGPUObject' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)	UrhoUWPDesktop	D:\projects\webrtc-mrvc-sample\UrhoUWPDesktop\UrhoApplication.cs	141	Active

**Comment by binxie33** [comment]
I checked the implementation of BackgroundRenderer::ConvertI420ToABGR and realized that texPtr is never used, so I simply passed 0 in as a workaround. The desktop app can be built now and works as expected.

**Comment by phongcao** [comment]
@binxie33 Thanks for reporting. I've just fixed that issue.
